# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Bilan et rétrospective - 6e session
author: Votre nom

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_reference_style: author_year
bibtex_bibfiles:
  - références.bib

sphinx:
  recursive_update: true
  config:
    html_theme_options:
      repository_provider: https://git.dti.crosemont.quebec
    html_context:
      gitlab_url: https://git.dti.crosemont.quebec/session-intensive
      gitlab_repo: rapportIndividuel
      gitlab_user: ""
      gitlab_version: main
      doc_path: source
        
# Information about where the book exists on the web
repository:
  url: https://git.dti.crosemont.quebec/session-intensive/rapportIndividuel  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: individuel  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
